config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :messages
  resources :insurers
  resources :doctors

  root 'static#index'
  get 'messages/approve/:id' => 'messages#approve'
  get 'messages/deny/:id' => 'messages#deny'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/insurer.rb
class Insurer < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])
    doctor_id = @doctor.id
    @messages = Message.where(["sender_id = ?", doctor_id])
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name)
    end
end

app/controllers/insurers_controller.rb
class InsurersController < ApplicationController
  before_action :set_insurer, only: [:show, :edit, :update, :destroy]

  # GET /insurers
  # GET /insurers.json
  def index
    @insurers = Insurer.all
  end

  # GET /insurers/1
  # GET /insurers/1.json
  def show
    @insurer = Insurer.find(params[:id])
    insurer_id = @insurer.id 
    @messages = Message.where(["receiver_id = ?", insurer_id])
  end

  # GET /insurers/new
  def new
    @insurer = Insurer.new
  end

  # GET /insurers/1/edit
  def edit
  end

  # POST /insurers
  # POST /insurers.json
  def create
    @insurer = Insurer.new(insurer_params)

    respond_to do |format|
      if @insurer.save
        format.html { redirect_to @insurer, notice: 'Insurer was successfully created.' }
        format.json { render :show, status: :created, location: @insurer }
      else
        format.html { render :new }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurers/1
  # PATCH/PUT /insurers/1.json
  def update
    respond_to do |format|
      if @insurer.update(insurer_params)
        format.html { redirect_to @insurer, notice: 'Insurer was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurer }
      else
        format.html { render :edit }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurers/1
  # DELETE /insurers/1.json
  def destroy
    @insurer.destroy
    respond_to do |format|
      format.html { redirect_to insurers_url, notice: 'Insurer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurer
      @insurer = Insurer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurer_params
      params.require(:insurer).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        doctor_id = @message.sender_id
        @doctor = Doctor.find(doctor_id)
        format.html { redirect_to @doctor, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @message = Message.find(params[:id])
    insurer_id = @message.receiver_id
    @message.authorization = 1
    @insurer = Insurer.find(insurer_id)
    @message.save
    redirect_to @insurer
  end

  def deny
    @message = Message.find(params[:id])
    insurer_id = @message.receiver_id
    @message.authorization = 0
    @insurer = Insurer.find(insurer_id)
    @message.save
    redirect_to @insurer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:authnum, :firstnamepatient, :lastnamepatient, :dob, :ethnicity, :gender, :icd10, :ndc11, :evidence, :nntval, :servicedate, :servicepriority, :servicesite, :firstnameordering, :lastnameordering, :npiordering, :phoneorering, :emailordering, :mailordering, :clientid, :planid, :planphone, :planfax, :memberid, :patientid, :authorization, :preauth, :seqid, :sender_id, :receiver_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/insurers_helper.rb
module InsurersHelper
end

app/helpers/math_helper.rb
module MathHelper
    
    def gomp p
       Math.exp(-3 * Math.exp(-1 * (p - 0.05) * 15)) 
    end
    
    def wrs (rs, p)
       if rs > 1
          if p > 0.05
              rs - ((rs - 1)*gomp(p))
          else
              rs
          end
       else
            if p > 0.05
               rs + ((1 - rs)*gomp(p))
            else
               rs
            end  
       end
    end
        
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<head>
  <% javascript_include_tag "doctors.js" %>
</head>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>
<div id="wrapper">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <div class="navbar-brand">Generic Company</div>
    </div>
    &nbsp;
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
      <!-- /.dropdown -->

      <!-- /.dropdown -->
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
          <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
          </li>
          <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
          </li>
          <li class="divider"></li>
          <li><a href="/pages/login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
          </li>
        </ul>
        <!-- /.dropdown-user -->
      </li>
      <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
    <!-- /.sidebar-collapse -->
  </nav></div>
<!-- /.navbar-static-side -->


<div id="page-wrapper">

  <div id="myModal" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3>New Request</h3>
        </div>
          <div class="modal-body">
            <%= form_for :message,  html:{ id:"user-form"}, url: messages_path do |f| %>
            <div class="row" id="authEngine">
              <div class="col-md-6">
                <h4 class="form-heading form-top">Patient Information</h4>
                <div class="form-group">
                  <label>Last Name:
                  </label>
                  <span><input class="form-control fill-form" name="p_Lname" autofocus="true"/></span>
                </div>
                <div class="form-group">
                  <label>First Name:
                  </label>
                  <span><input class="form-control fill-form" name="p_Fname" autofocus="true"/></span>
                </div>
                <div class="form-group">
                  <label>Birthdate:</label>
                  <span><input type="date" class="form-control" name="p_birthdate" value=""/></span>
                </div>
              </div>
              <div class="col-md-6 left-gutter-border">
                <h4 class="form-heading form-top">Diagnostic Attributes</h4>

                  <div class="form-group">
                    <label>Primary Diagnosis:</label>
                              <span><select class="form-control" name="diagnosis">
                                <option>Type 1</option>
                                <option>Type 2</option>
                                <option>Type 3</option>
                              </select></span>
                  </div>
              </div>
              <div class="col-md-12">
                <h4 class="form-heading">Treatment Select</h4>
                <div class="form-group treatmentContainer">

                </div>
              </div>
            </div>
            <div class="row inactive" id="authForm">

              <div class="col-md-6">
                <h4 class="form-heading form-top">Patient Information</h4>
                <div class="form-group">
                  <label>ID# or MRN:</label>
                  <span><input class="form-control" name="ins_id" value=""></span>
                </div>
                <div class="form-group">
                  <label>Insurance Name:
                  </label>
                  <span><input class="form-control fill-form" name="ins_Name" autofocus="true"/></span>
                </div>
                <div class="form-group">
                  <label>Insurance Plan:
                  </label>
                  <span><input class="form-control fill-form" name="ins_Plan" autofocus="true"/></span>
                </div>
              </div>
              <div class="col-md-6">
                <h4 class="form-heading form-top">Physician Information</h4>
                <!-- Change this to a button or input when using this as a form -->
                <div class="form-group">
                  <label>First Name:</label>
                  <span><input class="form-control" name="c_Fname"></span>
                </div>
                <div class="form-group">
                  <label>Last Name:</label>
                  <span><input class="form-control" name="c_Lname"></span>
                </div>
                <div class="form-group">
                  <label>ID #:</label>
                  <span><input class="form-control" name="c_id" value=""></span>
                </div>
                <div class="form-group">
                  <label>Phone Number:</label>
                  <span><input class="form-control" name="p_id" value=""></span>
                </div>
              </div>

              <div class="col-md-12">
                <h4 class="form-heading"> Rendering Provider</h4>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>ID#:</label>
                      <span><input class="form-control" name="r_id" value=""></span>
                    </div>
                    <div class="form-group">
                      <label>Name:</label>
                      <span><input class="form-control" name="r_name"></span>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Role:</label>
                      <span><input class="form-control" name="r_role"></span>
                    </div>
                    <div class="form-group">
                      <label>Speciality:</label>
                      <span><input class="form-control" name="s_type" value=""></span>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-md-12">
                <h4 class="form-heading">Care Rendered</h4>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Request Type:</label>
                      <span><input class="form-control" name="req_type"></span>
                    </div>
                    <div class="form-group">
                      <label>Level of Care:</label>
                            <span><select class="form-control" name="serv_level">
                              <option>Elective</option>
                              <option>Urgent</option>
                              <option>Emergency</option>
                            </select></span>
                    </div>
                    <div class="form-group">
                      <label>Service Date:</label>
                      <span><input type="date" class="form-control" name="serv_date" value=""></span>
                    </div>
                    <div class="form-group">
                      <label>Number of Visits:</label>
                      <span><input class="form-control" type="number" name="serv_site" value=""></span>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Site of Service:</label>
                      <span><input class="form-control" name="serv_site" value=""></span>
                    </div>
                    <div class="form-group">
                      <label>Admission Date:</label>
                      <span><input type="date" class="form-control" name="admit_date" value=""></span>
                    </div>
                    <div class="form-group">
                      <label>Diagnosis Code:</label>
                      <span><input class="form-control" name="serv_site" value=""></span>
                    </div>

                  </div>
                </div>
              </div>
            </div>

          </div>
          <div class="modal-footer">
            <div id="authButtons">
              <button type="button" id="authTransition" class="btn btn-default btn-primary">Next</button>
              <button id="earlyCancelModal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            <div id="submitButtons" class="inactive">
              <%= f.submit id:"addRequest", class:"btn btn-default btn-primary" %>
              <button id="backTransition" type="button" class="btn btn-default">Back</button>
              <button id="closeModal" type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>


  <div class="row">
    <div class="col-lg-12 page-header">
      <div class="row">
        <div class="col-sm-1">
          <h3 class="sub-page-header">Requests</h3>
        </div>
        <div class="col-sm-11" id="">
          <div>
            <input type="search" class="form-control master-search" placeholder="" aria-controls="dataTables-example">
            <button>Search</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <!-- /.panel-heading -->
      <div class="row">
        <div class="col-sm-1 right-gutter-border-bold full-sidebar">
          <button class="btn btn-sm btn-primary btn-action" data-toggle="modal" data-target="#myModal">New Request</button>
          <div class="filter-toggle active" id="allReqs">All Requests <span id="all-num"></span></div>
          <div class="filter-toggle" id="appReqs">In Progress</div>
          <div class="filter-toggle" id="appReqs">Approved</div>
          <div class="filter-toggle" id="denReqs">Denied</div>
          <div class="filter-toggle" id="arcReqs">Archived</div>
        </div>
        <div class="col-sm-11">
     
          <table class="table table-bordered table-hover dataTable no-footer" id="xtable">
            <thead>
              <tr>
                <th>Name</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @messages.each do |m| %>
                <tr>
                  <td><%= m.authnum %></td>
                  <td><%= m.sender_id %></td>
              <% end %>
            </tbody>
          </table>        
        </div>
      </div>
    </div>
  </div>
</div>     
<%= link_to 'New Message', new_message_path %>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/insurers/_form.html.erb
<%= form_for(@insurer) do |f| %>
  <% if @insurer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurer.errors.count, "error") %> prohibited this insurer from being saved:</h2>

      <ul>
      <% @insurer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insurers/edit.html.erb
<h1>Editing Insurer</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurer %> |
<%= link_to 'Back', insurers_path %>

app/views/insurers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insurers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurers.each do |insurer| %>
      <tr>
        <td><%= insurer.name %></td>
        <td><%= link_to 'Show', insurer %></td>
        <td><%= link_to 'Edit', edit_insurer_path(insurer) %></td>
        <td><%= link_to 'Destroy', insurer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurer', new_insurer_path %>

app/views/insurers/new.html.erb
<h1>New Insurer</h1>

<%= render 'form' %>

<%= link_to 'Back', insurers_path %>

app/views/insurers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insurer.name %>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
<% @messages.each do |m| %>
<tr>
        <td><%= m.authnum %></td>
        <td><%= m.sender_id %></td>
        <td><%= link_to 'approve', controller: "messages", action:"approve", id: m.id %>
        <td><%= link_to 'deny', controller: "messages", action:"deny", id: m.id %>

    <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_insurer_path(@insurer) %> |
<%= link_to 'Back', insurers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>TripleWebPrototype</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>

  <%= csrf_meta_tags %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

  <![endif]-->

</head>
<body>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Authnum</th>
      <th>Firstnamepatient</th>
      <th>Lastnamepatient</th>
      <th>Dob</th>
      <th>Ethnicity</th>
      <th>Gender</th>
      <th>Icd10</th>
      <th>Ndc11</th>
      <th>Evidence</th>
      <th>Nntval</th>
      <th>Servicedate</th>
      <th>Servicepriority</th>
      <th>Servicesite</th>
      <th>Firstnameordering</th>
      <th>Lastnameordering</th>
      <th>Npiordering</th>
      <th>Phoneorering</th>
      <th>Emailordering</th>
      <th>Mailordering</th>
      <th>Clientid</th>
      <th>Planid</th>
      <th>Planphone</th>
      <th>Planfax</th>
      <th>Memberid</th>
      <th>Patientid</th>
      <th>Authorization</th>
      <th>Preauth</th>
      <th>Seqid</th>
      <th>Senderid</th>
      <th>Receiverid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.authnum %></td>
        <td><%= message.firstnamepatient %></td>
        <td><%= message.lastnamepatient %></td>
        <td><%= message.dob %></td>
        <td><%= message.ethnicity %></td>
        <td><%= message.gender %></td>
        <td><%= message.icd10 %></td>
        <td><%= message.ndc11 %></td>
        <td><%= message.evidence %></td>
        <td><%= message.nntval %></td>
        <td><%= message.servicedate %></td>
        <td><%= message.servicepriority %></td>
        <td><%= message.servicesite %></td>
        <td><%= message.firstnameordering %></td>
        <td><%= message.lastnameordering %></td>
        <td><%= message.npiordering %></td>
        <td><%= message.phoneorering %></td>
        <td><%= message.emailordering %></td>
        <td><%= message.mailordering %></td>
        <td><%= message.clientid %></td>
        <td><%= message.planid %></td>
        <td><%= message.planphone %></td>
        <td><%= message.planfax %></td>
        <td><%= message.memberid %></td>
        <td><%= message.patientid %></td>
        <td><%= message.authorization %></td>
        <td><%= message.preauth %></td>
        <td><%= message.seqid %></td>
        <td><%= message.sender_id %></td>
        <td><%= message.receiver_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Authnum:</strong>
  <%= @message.authnum %>
</p>

<p>
  <strong>Firstnamepatient:</strong>
  <%= @message.firstnamepatient %>
</p>

<p>
  <strong>Lastnamepatient:</strong>
  <%= @message.lastnamepatient %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @message.dob %>
</p>

<p>
  <strong>Ethnicity:</strong>
  <%= @message.ethnicity %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @message.gender %>
</p>

<p>
  <strong>Icd10:</strong>
  <%= @message.icd10 %>
</p>

<p>
  <strong>Ndc11:</strong>
  <%= @message.ndc11 %>
</p>

<p>
  <strong>Evidence:</strong>
  <%= @message.evidence %>
</p>

<p>
  <strong>Nntval:</strong>
  <%= @message.nntval %>
</p>

<p>
  <strong>Servicedate:</strong>
  <%= @message.servicedate %>
</p>

<p>
  <strong>Servicepriority:</strong>
  <%= @message.servicepriority %>
</p>

<p>
  <strong>Servicesite:</strong>
  <%= @message.servicesite %>
</p>

<p>
  <strong>Firstnameordering:</strong>
  <%= @message.firstnameordering %>
</p>

<p>
  <strong>Lastnameordering:</strong>
  <%= @message.lastnameordering %>
</p>

<p>
  <strong>Npiordering:</strong>
  <%= @message.npiordering %>
</p>

<p>
  <strong>Phoneorering:</strong>
  <%= @message.phoneorering %>
</p>

<p>
  <strong>Emailordering:</strong>
  <%= @message.emailordering %>
</p>

<p>
  <strong>Mailordering:</strong>
  <%= @message.mailordering %>
</p>

<p>
  <strong>Clientid:</strong>
  <%= @message.clientid %>
</p>

<p>
  <strong>Planid:</strong>
  <%= @message.planid %>
</p>

<p>
  <strong>Planphone:</strong>
  <%= @message.planphone %>
</p>

<p>
  <strong>Planfax:</strong>
  <%= @message.planfax %>
</p>

<p>
  <strong>Memberid:</strong>
  <%= @message.memberid %>
</p>

<p>
  <strong>Patientid:</strong>
  <%= @message.patientid %>
</p>

<p>
  <strong>Authorization:</strong>
  <%= @message.authorization %>
</p>

<p>
  <strong>Preauth:</strong>
  <%= @message.preauth %>
</p>

<p>
  <strong>Seqid:</strong>
  <%= @message.seqid %>
</p>

<p>
  <strong>Senderid:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Receiverid:</strong>
  <%= @message.receiver_id %>
</p>

<% doctor_id = @message.sender_id %>
<% @doctor = Doctor.find([doctor_id]) %>
<%= link_to 'Doctor', doctor_path(@doctor) %>
<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>